// <auto-generated />
namespace OffTheLipProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Añadir_Comentarios_Likes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Añadir_Comentarios_Likes));
        
        string IMigrationMetadata.Id
        {
            get { return "201911141832481_Añadir_Comentarios_Likes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
